package es.bootools.touchbar.model;

// Generated 30-jul-2012 20:27:59 by Hibernate Tools 4.0.0

import static javax.persistence.GenerationType.IDENTITY;

import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Cliente generated by hbm2java
 */
@Entity
@Table(name = "cliente", catalog = "touchbar")
public class Cliente implements java.io.Serializable {

	private Integer idCliente;
	private String codCliente;
	private String password;
	private String codUnicoMovil;
	private String nombre;
	private String apellido1;
	private String apellido2;
	private String telefonoFijo;
	private String telefonoMovil;
	private String correoElectronico;
	private String usuCrear;
	private Date fechaCrear;
	private String usuModificar;
	private Date fechaModificar;
	private String usuBorrar;
	private Date fechaBorrar;

	// private Set<Pedido> pedidos = new HashSet<Pedido>(0);

	public Cliente() {
	}

	public Cliente(String codCliente, String password, String codUnicoMovil,
			String nombre, String apellido1, String apellido2,
			String telefonoFijo, String telefonoMovil,
			String correoElectronico, String usuCrear, Date fechaCrear,
			String usuModificar, Date fechaModificar, String usuBorrar,
			Date fechaBorrar) {
		this.codCliente = codCliente;
		this.password = password;
		this.codUnicoMovil = codUnicoMovil;
		this.nombre = nombre;
		this.apellido1 = apellido1;
		this.apellido2 = apellido2;
		this.telefonoFijo = telefonoFijo;
		this.telefonoMovil = telefonoMovil;
		this.correoElectronico = correoElectronico;
		this.usuCrear = usuCrear;
		this.fechaCrear = fechaCrear;
		this.usuModificar = usuModificar;
		this.fechaModificar = fechaModificar;
		this.usuBorrar = usuBorrar;
		this.fechaBorrar = fechaBorrar;
		// this.pedidos = pedidos;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id_cliente", unique = true, nullable = false)
	public Integer getIdCliente() {
		return this.idCliente;
	}

	public void setIdCliente(Integer idCliente) {
		this.idCliente = idCliente;
	}

	@Column(name = "cod_cliente", length = 45)
	public String getCodCliente() {
		return this.codCliente;
	}

	public void setCodCliente(String codCliente) {
		this.codCliente = codCliente;
	}

	@Column(name = "password", length = 45)
	public String getPassword() {
		return this.password;
	}

	public void setPassword(String password) {
		this.password = password;
	}

	@Column(name = "cod_unico_movil", length = 45)
	public String getCodUnicoMovil() {
		return this.codUnicoMovil;
	}

	public void setCodUnicoMovil(String codUnicoMovil) {
		this.codUnicoMovil = codUnicoMovil;
	}

	@Column(name = "nombre", length = 60)
	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	@Column(name = "apellido1", length = 60)
	public String getApellido1() {
		return this.apellido1;
	}

	public void setApellido1(String apellido1) {
		this.apellido1 = apellido1;
	}

	@Column(name = "apellido2", length = 60)
	public String getApellido2() {
		return this.apellido2;
	}

	public void setApellido2(String apellido2) {
		this.apellido2 = apellido2;
	}

	@Column(name = "telefono_fijo", length = 15)
	public String getTelefonoFijo() {
		return this.telefonoFijo;
	}

	public void setTelefonoFijo(String telefonoFijo) {
		this.telefonoFijo = telefonoFijo;
	}

	@Column(name = "telefono_movil", length = 15)
	public String getTelefonoMovil() {
		return this.telefonoMovil;
	}

	public void setTelefonoMovil(String telefonoMovil) {
		this.telefonoMovil = telefonoMovil;
	}

	@Column(name = "correo_electronico", length = 60)
	public String getCorreoElectronico() {
		return this.correoElectronico;
	}

	public void setCorreoElectronico(String correoElectronico) {
		this.correoElectronico = correoElectronico;
	}

	@Column(name = "usu_crear", length = 45)
	public String getUsuCrear() {
		return this.usuCrear;
	}

	public void setUsuCrear(String usuCrear) {
		this.usuCrear = usuCrear;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "fecha_crear", length = 19)
	public Date getFechaCrear() {
		return this.fechaCrear;
	}

	public void setFechaCrear(Date fechaCrear) {
		this.fechaCrear = fechaCrear;
	}

	@Column(name = "usu_modificar", length = 45)
	public String getUsuModificar() {
		return this.usuModificar;
	}

	public void setUsuModificar(String usuModificar) {
		this.usuModificar = usuModificar;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "fecha_modificar", length = 19)
	public Date getFechaModificar() {
		return this.fechaModificar;
	}

	public void setFechaModificar(Date fechaModificar) {
		this.fechaModificar = fechaModificar;
	}

	@Column(name = "usu_borrar", length = 45)
	public String getUsuBorrar() {
		return this.usuBorrar;
	}

	public void setUsuBorrar(String usuBorrar) {
		this.usuBorrar = usuBorrar;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "fecha_borrar", length = 19)
	public Date getFechaBorrar() {
		return this.fechaBorrar;
	}

	public void setFechaBorrar(Date fechaBorrar) {
		this.fechaBorrar = fechaBorrar;
	}

	// @OneToMany(fetch = FetchType.LAZY, mappedBy = "cliente")
	// public Set<Pedido> getPedidos() {
	// return this.pedidos;
	// }
	//
	// public void setPedidos(Set<Pedido> pedidos) {
	// this.pedidos = pedidos;
	// }

}
