package es.bootools.touchbar.model;

// Generated 30-jul-2012 20:27:59 by Hibernate Tools 4.0.0

import static javax.persistence.GenerationType.IDENTITY;

import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * DestinoProducto generated by hbm2java
 */
@Entity
@Table(name = "destino_producto", catalog = "touchbar")
public class DestinoProducto implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = -9193385872244072062L;
	private Integer idDestinoProducto;
	private String nombre;
	private String descripcion;
	private String impresora;
	private String usuCrear;
	private Date fechaModificar;
	private String usuModificar;
	private Date fechaCrear;
	private String usuBorrar;
	private Date fechaBorrar;

	public DestinoProducto() {
	}

	public DestinoProducto(Integer idDestinoProducto) {
		this.idDestinoProducto = idDestinoProducto;
	}

	public DestinoProducto(Integer idDestinoProducto, String nombre,
			String descripcion, String impresora, String usuCrear,
			Date fechaModificar, String usuModificar, Date fechaCrear,
			String usuBorrar, Date fechaBorrar) {
		this.idDestinoProducto = idDestinoProducto;
		this.nombre = nombre;
		this.descripcion = descripcion;
		this.impresora = impresora;
		this.usuCrear = usuCrear;
		this.fechaModificar = fechaModificar;
		this.usuModificar = usuModificar;
		this.fechaCrear = fechaCrear;
		this.usuBorrar = usuBorrar;
		this.fechaBorrar = fechaBorrar;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id_destino_producto", unique = true, nullable = false)
	public Integer getIdDestinoProducto() {
		return this.idDestinoProducto;
	}

	public void setIdDestinoProducto(Integer idDestinoProducto) {
		this.idDestinoProducto = idDestinoProducto;
	}

	@Column(name = "nombre", length = 60)
	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	@Column(name = "descripcion", length = 300)
	public String getDescripcion() {
		return this.descripcion;
	}

	public void setDescripcion(String descripcion) {
		this.descripcion = descripcion;
	}

	@Column(name = "impresora", length = 45)
	public String getImpresora() {
		return this.impresora;
	}

	public void setImpresora(String impresora) {
		this.impresora = impresora;
	}

	@Column(name = "usu_crear", length = 45)
	public String getUsuCrear() {
		return this.usuCrear;
	}

	public void setUsuCrear(String usuCrear) {
		this.usuCrear = usuCrear;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "fecha_modificar", length = 19)
	public Date getFechaModificar() {
		return this.fechaModificar;
	}

	public void setFechaModificar(Date fechaModificar) {
		this.fechaModificar = fechaModificar;
	}

	@Column(name = "usu_modificar", length = 45)
	public String getUsuModificar() {
		return this.usuModificar;
	}

	public void setUsuModificar(String usuModificar) {
		this.usuModificar = usuModificar;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "fecha_crear", length = 19)
	public Date getFechaCrear() {
		return this.fechaCrear;
	}

	public void setFechaCrear(Date fechaCrear) {
		this.fechaCrear = fechaCrear;
	}

	@Column(name = "usu_borrar", length = 45)
	public String getUsuBorrar() {
		return this.usuBorrar;
	}

	public void setUsuBorrar(String usuBorrar) {
		this.usuBorrar = usuBorrar;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "fecha_borrar", length = 19)
	public Date getFechaBorrar() {
		return this.fechaBorrar;
	}

	public void setFechaBorrar(Date fechaBorrar) {
		this.fechaBorrar = fechaBorrar;
	}

	// @ManyToMany(fetch = FetchType.LAZY)
	// @JoinTable(name = "destino_producto_has_rol", catalog = "touchbar",
	// joinColumns = { @JoinColumn(name = "id_destino_producto", nullable =
	// false, updatable = false) }, inverseJoinColumns = { @JoinColumn(name =
	// "id_rol", nullable = false, updatable = false) })
	// public Set<Rol> getRols() {
	// return this.rols;
	// }
	//
	// public void setRols(Set<Rol> rols) {
	// this.rols = rols;
	// }
	//
	// @OneToMany(fetch = FetchType.LAZY, mappedBy = "destinoProducto")
	// public Set<Producto> getProductos() {
	// return this.productos;
	// }
	//
	// public void setProductos(Set<Producto> productos) {
	// this.productos = productos;
	// }

}
