package es.bootools.touchbar.model;

// Generated 30-jul-2012 20:27:59 by Hibernate Tools 4.0.0

import static javax.persistence.GenerationType.IDENTITY;

import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Pedido generated by hbm2java
 */
@Entity
@Table(name = "pedido", catalog = "touchbar")
public class Pedido implements java.io.Serializable {

	private Integer idPedido;
	private Cliente cliente;
	private Date fechaPedido;
	private String mesa;
	private Boolean servido;
	private String comentario;
	private String usuCrear;
	private Date fechaCrear;
	private String usuModificar;
	private Date fechaModificar;
	private String usuBorrar;
	private Date fechaBorrar;

	// private Set<ProductoPedido> productoPedidos = new
	// HashSet<ProductoPedido>(0);

	public Pedido() {
	}

	public Pedido(Integer idPedido, Cliente cliente) {
		this.idPedido = idPedido;
		this.cliente = cliente;
	}

	public Pedido(Integer idPedido, Cliente cliente, Date fechaPedido, String mesa,
			Boolean servido, String comentario, String usuCrear,
			Date fechaCrear, String usuModificar, Date fechaModificar,
			String usuBorrar, Date fechaBorrar) {
		this.idPedido = idPedido;
		this.cliente = cliente;
		this.fechaPedido = fechaPedido;
		this.mesa = mesa;
		this.servido = servido;
		this.comentario = comentario;
		this.usuCrear = usuCrear;
		this.fechaCrear = fechaCrear;
		this.usuModificar = usuModificar;
		this.fechaModificar = fechaModificar;
		this.usuBorrar = usuBorrar;
		this.fechaBorrar = fechaBorrar;
		// this.productoPedidos = productoPedidos;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id_pedido", unique = true, nullable = false)
	public Integer getIdPedido() {
		return this.idPedido;
	}

	public void setIdPedido(Integer idPedido) {
		this.idPedido = idPedido;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_cliente", nullable = false)
	public Cliente getCliente() {
		return this.cliente;
	}

	public void setCliente(Cliente cliente) {
		this.cliente = cliente;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "fecha_pedido", length = 19)
	public Date getFechaPedido() {
		return this.fechaPedido;
	}

	public void setFechaPedido(Date fechaPedido) {
		this.fechaPedido = fechaPedido;
	}

	@Column(name = "mesa", length = 45)
	public String getMesa() {
		return this.mesa;
	}

	public void setMesa(String mesa) {
		this.mesa = mesa;
	}

	@Column(name = "servido")
	public Boolean getServido() {
		return this.servido;
	}

	public void setServido(Boolean servido) {
		this.servido = servido;
	}

	@Column(name = "comentario", length = 300)
	public String getComentario() {
		return this.comentario;
	}

	public void setComentario(String comentario) {
		this.comentario = comentario;
	}

	@Column(name = "usu_crear", length = 45)
	public String getUsuCrear() {
		return this.usuCrear;
	}

	public void setUsuCrear(String usuCrear) {
		this.usuCrear = usuCrear;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "fecha_crear", length = 19)
	public Date getFechaCrear() {
		return this.fechaCrear;
	}

	public void setFechaCrear(Date fechaCrear) {
		this.fechaCrear = fechaCrear;
	}

	@Column(name = "usu_modificar", length = 45)
	public String getUsuModificar() {
		return this.usuModificar;
	}

	public void setUsuModificar(String usuModificar) {
		this.usuModificar = usuModificar;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "fecha_modificar", length = 19)
	public Date getFechaModificar() {
		return this.fechaModificar;
	}

	public void setFechaModificar(Date fechaModificar) {
		this.fechaModificar = fechaModificar;
	}

	@Column(name = "usu_borrar", length = 45)
	public String getUsuBorrar() {
		return this.usuBorrar;
	}

	public void setUsuBorrar(String usuBorrar) {
		this.usuBorrar = usuBorrar;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "fecha_borrar", length = 19)
	public Date getFechaBorrar() {
		return this.fechaBorrar;
	}

	public void setFechaBorrar(Date fechaBorrar) {
		this.fechaBorrar = fechaBorrar;
	}

	// @OneToMany(fetch = FetchType.LAZY, mappedBy = "pedido")
	// public Set<ProductoPedido> getProductoPedidos() {
	// return this.productoPedidos;
	// }
	//
	// public void setProductoPedidos(Set<ProductoPedido> productoPedidos) {
	// this.productoPedidos = productoPedidos;
	// }

}
