package es.bootools.touchbar.model;

// Generated 30-jul-2012 20:27:59 by Hibernate Tools 4.0.0

import static javax.persistence.GenerationType.IDENTITY;

import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * ProductoPedido generated by hbm2java
 */
@Entity
@Table(name = "producto_pedido", catalog = "touchbar")
public class ProductoPedido implements java.io.Serializable {

	private Integer idProductoPedido;
	private Pedido pedido;
	private Producto producto;
	private String comentario;
	private Boolean servido;
	private String usuCrear;
	private Date fechaCrear;
	private String usuModificar;
	private Date fechaModificar;
	private String usuBorrar;
	private Date fechaBorrar;

	public ProductoPedido() {
	}

	public ProductoPedido(Integer idProductoPedido, Pedido pedido,
			Producto producto) {
		this.idProductoPedido = idProductoPedido;
		this.pedido = pedido;
		this.producto = producto;
	}

	public ProductoPedido(Integer idProductoPedido, Pedido pedido,
			Producto producto, String comentario, Boolean servido,
			String usuCrear, Date fechaCrear, String usuModificar,
			Date fechaModificar, String usuBorrar, Date fechaBorrar) {
		this.idProductoPedido = idProductoPedido;
		this.pedido = pedido;
		this.producto = producto;
		this.comentario = comentario;
		this.servido = servido;
		this.usuCrear = usuCrear;
		this.fechaCrear = fechaCrear;
		this.usuModificar = usuModificar;
		this.fechaModificar = fechaModificar;
		this.usuBorrar = usuBorrar;
		this.fechaBorrar = fechaBorrar;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id_producto_pedido", unique = true, nullable = false)
	public Integer getIdProductoPedido() {
		return this.idProductoPedido;
	}

	public void setIdProductoPedido(Integer idProductoPedido) {
		this.idProductoPedido = idProductoPedido;
	}

	@ManyToOne(targetEntity = Pedido.class, fetch = FetchType.LAZY)
	@JoinColumn(name = "id_pedido", nullable = false)
	public Pedido getPedido() {
		return this.pedido;
	}

	public void setPedido(Pedido pedido) {
		this.pedido = pedido;
	}

	@ManyToOne(targetEntity = Producto.class, fetch = FetchType.LAZY)
	@JoinColumn(name = "id_producto", nullable = false)
	public Producto getProducto() {
		return this.producto;
	}

	public void setProducto(Producto producto) {
		this.producto = producto;
	}

	@Column(name = "comentario", length = 300)
	public String getComentario() {
		return this.comentario;
	}

	public void setComentario(String comentario) {
		this.comentario = comentario;
	}

	@Column(name = "servido")
	public Boolean getServido() {
		return this.servido;
	}

	public void setServido(Boolean servido) {
		this.servido = servido;
	}

	@Column(name = "usu_crear", length = 45)
	public String getUsuCrear() {
		return this.usuCrear;
	}

	public void setUsuCrear(String usuCrear) {
		this.usuCrear = usuCrear;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "fecha_crear", length = 19)
	public Date getFechaCrear() {
		return this.fechaCrear;
	}

	public void setFechaCrear(Date fechaCrear) {
		this.fechaCrear = fechaCrear;
	}

	@Column(name = "usu_modificar", length = 45)
	public String getUsuModificar() {
		return this.usuModificar;
	}

	public void setUsuModificar(String usuModificar) {
		this.usuModificar = usuModificar;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "fecha_modificar", length = 19)
	public Date getFechaModificar() {
		return this.fechaModificar;
	}

	public void setFechaModificar(Date fechaModificar) {
		this.fechaModificar = fechaModificar;
	}

	@Column(name = "usu_borrar", length = 45)
	public String getUsuBorrar() {
		return this.usuBorrar;
	}

	public void setUsuBorrar(String usuBorrar) {
		this.usuBorrar = usuBorrar;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "fecha_borrar", length = 19)
	public Date getFechaBorrar() {
		return this.fechaBorrar;
	}

	public void setFechaBorrar(Date fechaBorrar) {
		this.fechaBorrar = fechaBorrar;
	}
}
