package es.bootools.touchbar.model;

// Generated 30-jul-2012 20:27:59 by Hibernate Tools 4.0.0

import static javax.persistence.GenerationType.IDENTITY;

import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Producto generated by hbm2java
 */
@Entity
@Table(name = "producto", catalog = "touchbar")
public class Producto implements java.io.Serializable {

	private Integer idProducto;
	private GrupoProducto grupoProducto;
	private DestinoProducto destinoProducto;
	private Boolean publicado;
	private String nombre;
	private String descripcion;
	private String precio;
	private String imagen;
	private String usuCrear;
	private Date fechaCrear;
	private String usuModificar;
	private Date fechaModificar;
	private String usuBorrar;
	private Date fechaBorrar;

	// private Set<ProductoPedido> productoPedidos = new
	// HashSet<ProductoPedido>(0);

	public Producto() {
	}

	public Producto(Integer idProducto, GrupoProducto grupoProducto,
			DestinoProducto destinoProducto) {
		this.idProducto = idProducto;
		this.grupoProducto = grupoProducto;
		this.destinoProducto = destinoProducto;
	}

	public Producto(Integer idProducto, GrupoProducto grupoProducto,
			DestinoProducto destinoProducto, Boolean publicado, String nombre,
			String descripcion, String precio, String imagen, String usuCrear,
			Date fechaCrear, String usuModificar, Date fechaModificar,
			String usuBorrar, Date fechaBorrar) {
		this.idProducto = idProducto;
		this.grupoProducto = grupoProducto;
		this.destinoProducto = destinoProducto;
		this.publicado = publicado;
		this.nombre = nombre;
		this.descripcion = descripcion;
		this.precio = precio;
		this.imagen = imagen;
		this.usuCrear = usuCrear;
		this.fechaCrear = fechaCrear;
		this.usuModificar = usuModificar;
		this.fechaModificar = fechaModificar;
		this.usuBorrar = usuBorrar;
		this.fechaBorrar = fechaBorrar;
		// this.productoPedidos = productoPedidos;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id_producto", unique = true, nullable = false)
	public Integer getIdProducto() {
		return this.idProducto;
	}

	public void setIdProducto(Integer idProducto) {
		this.idProducto = idProducto;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_grupo_producto", nullable = false)
	public GrupoProducto getGrupoProducto() {
		return this.grupoProducto;
	}

	public void setGrupoProducto(GrupoProducto grupoProducto) {
		this.grupoProducto = grupoProducto;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_destino_producto", nullable = false)
	public DestinoProducto getDestinoProducto() {
		return this.destinoProducto;
	}

	public void setDestinoProducto(DestinoProducto destinoProducto) {
		this.destinoProducto = destinoProducto;
	}

	@Column(name = "publicado")
	public Boolean getPublicado() {
		return this.publicado;
	}

	public void setPublicado(Boolean publicado) {
		this.publicado = publicado;
	}

	@Column(name = "nombre", length = 60)
	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	@Column(name = "descripcion", length = 300)
	public String getDescripcion() {
		return this.descripcion;
	}

	public void setDescripcion(String descripcion) {
		this.descripcion = descripcion;
	}

	@Column(name = "precio", length = 45)
	public String getPrecio() {
		return this.precio;
	}

	public void setPrecio(String precio) {
		this.precio = precio;
	}

	@Column(name = "imagen", length = 300)
	public String getImagen() {
		return this.imagen;
	}

	public void setImagen(String imagen) {
		this.imagen = imagen;
	}

	@Column(name = "usu_crear", length = 45)
	public String getUsuCrear() {
		return this.usuCrear;
	}

	public void setUsuCrear(String usuCrear) {
		this.usuCrear = usuCrear;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "fecha_crear", length = 19)
	public Date getFechaCrear() {
		return this.fechaCrear;
	}

	public void setFechaCrear(Date fechaCrear) {
		this.fechaCrear = fechaCrear;
	}

	@Column(name = "usu_modificar", length = 45)
	public String getUsuModificar() {
		return this.usuModificar;
	}

	public void setUsuModificar(String usuModificar) {
		this.usuModificar = usuModificar;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "fecha_modificar", length = 19)
	public Date getFechaModificar() {
		return this.fechaModificar;
	}

	public void setFechaModificar(Date fechaModificar) {
		this.fechaModificar = fechaModificar;
	}

	@Column(name = "usu_borrar", length = 45)
	public String getUsuBorrar() {
		return this.usuBorrar;
	}

	public void setUsuBorrar(String usuBorrar) {
		this.usuBorrar = usuBorrar;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "fecha_borrar", length = 19)
	public Date getFechaBorrar() {
		return this.fechaBorrar;
	}

	public void setFechaBorrar(Date fechaBorrar) {
		this.fechaBorrar = fechaBorrar;
	}

}
