package es.bootools.touchbar.model;

// Generated 30-jul-2012 20:27:59 by Hibernate Tools 4.0.0

import static javax.persistence.GenerationType.IDENTITY;

import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Rol generated by hbm2java
 */
@Entity
@Table(name = "rol", catalog = "touchbar")
public class Rol implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = -5992463067457856123L;
	private Integer idRol;
	private DestinoProducto destinoProducto;
	private String nombre;
	private String descripcion;
	private String usuCrear;
	private Date fechaCrear;
	private String usuModificar;
	private Date fechaModificar;
	private String usuBorrar;
	private Date fechaBorrar;

	// private Set<Empleado> empleados = new HashSet<Empleado>(0);
	// private Set<DestinoProducto> destinoProductos = new
	// HashSet<DestinoProducto>(0);

	public Rol() {
	}

	public Rol(Integer idRol, DestinoProducto destinoProducto) {
		this.idRol = idRol;
		this.destinoProducto = destinoProducto;
	}

	public Rol(Integer idRol, DestinoProducto destinoProducto, String nombre,
			String descripcion, String usuCrear, Date fechaCrear,
			String usuModificar, Date fechaModificar, String usuBorrar,
			Date fechaBorrar) {
		this.idRol = idRol;
		this.destinoProducto = destinoProducto;
		this.nombre = nombre;
		this.descripcion = descripcion;
		this.usuCrear = usuCrear;
		this.fechaCrear = fechaCrear;
		this.usuModificar = usuModificar;
		this.fechaModificar = fechaModificar;
		this.usuBorrar = usuBorrar;
		this.fechaBorrar = fechaBorrar;
		// this.empleados = empleados;
		// this.destinoProductos = destinoProductos;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id_rol", unique = true, nullable = false)
	public Integer getIdRol() {
		return this.idRol;
	}

	public void setIdRol(Integer idRol) {
		this.idRol = idRol;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_destino_producto", nullable = false)
	public DestinoProducto getDestinoProducto() {
		return this.destinoProducto;
	}

	public void setDestinoProducto(DestinoProducto destinoProducto) {
		this.destinoProducto = destinoProducto;
	}

	@Column(name = "nombre", length = 60)
	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	@Column(name = "descripcion", length = 300)
	public String getDescripcion() {
		return this.descripcion;
	}

	public void setDescripcion(String descripcion) {
		this.descripcion = descripcion;
	}

	@Column(name = "usu_crear", length = 45)
	public String getUsuCrear() {
		return this.usuCrear;
	}

	public void setUsuCrear(String usuCrear) {
		this.usuCrear = usuCrear;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "fecha_crear", length = 19)
	public Date getFechaCrear() {
		return this.fechaCrear;
	}

	public void setFechaCrear(Date fechaCrear) {
		this.fechaCrear = fechaCrear;
	}

	@Column(name = "usu_modificar", length = 45)
	public String getUsuModificar() {
		return this.usuModificar;
	}

	public void setUsuModificar(String usuModificar) {
		this.usuModificar = usuModificar;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "fecha_modificar", length = 19)
	public Date getFechaModificar() {
		return this.fechaModificar;
	}

	public void setFechaModificar(Date fechaModificar) {
		this.fechaModificar = fechaModificar;
	}

	@Column(name = "usu_borrar", length = 45)
	public String getUsuBorrar() {
		return this.usuBorrar;
	}

	public void setUsuBorrar(String usuBorrar) {
		this.usuBorrar = usuBorrar;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "fecha_borrar", length = 19)
	public Date getFechaBorrar() {
		return this.fechaBorrar;
	}

	public void setFechaBorrar(Date fechaBorrar) {
		this.fechaBorrar = fechaBorrar;
	}

	// @OneToMany(fetch = FetchType.LAZY, mappedBy = "rol")
	// public Set<Empleado> getEmpleados() {
	// return this.empleados;
	// }
	//
	// public void setEmpleados(Set<Empleado> empleados) {
	// this.empleados = empleados;
	// }
	//
	// @ManyToMany(fetch = FetchType.LAZY, mappedBy = "rols")
	// public Set<DestinoProducto> getDestinoProductos() {
	// return this.destinoProductos;
	// }
	//
	// public void setDestinoProductos(Set<DestinoProducto> destinoProductos) {
	// this.destinoProductos = destinoProductos;
	// }

}
